### PR TITLE
Making tags for roles optional

### PR DESCRIPTION
**Pull request by jamengual**
## what
* Make role tags optional
*
## why
* Restrictive policy boundaries do not allow tag roles in highly secure environments.

### CODE REVIEW

**Comment by aknysh** [comment]
@jamengual thank you for the PR, please review these errors

```
Error: Unsupported attribute

  on .terraform/modules/bucket/main.tf line [34](https://github.com/cloudposse/actions/runs/5777893853?check_suite_focus=true#step:9:34), in resource "aws_s3_bucket" "default":
  34:       for_each = var.enable_glacier_transition ? [1] : []

This object does not have an attribute named "enable_glacier_transition".


Error: Unsupported attribute

  on .terraform/modules/bucket/main.tf line 43, in resource "aws_s3_bucket" "default":
  43:       for_each = var.enable_standard_ia_transition ? [1] : []
```

**Review by aknysh — DISMISSED** [review]
please see comments

**Comment by jamengual** [comment]
But But But I never changed any of those attributes....

**Comment by jamengual** [comment]
@aknysh fixed

**Review by Gowiem — APPROVED** [review]
I assume we're good with capping the example AWS provider version... Doesn't actually affect this module so I am good with it at least 

LGTM 👍

**Pull request merged**
